# Generated by Django 5.2.8 on 2026-02-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('thumb_small', models.TextField()),
                ('thumb_large', models.TextField()),
                ('embed_code', models.TextField(help_text='Raw iframe HTML')),
                ('pub_date', models.DateTimeField()),
                ('site', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=50)),
                ('tags', models.TextField()),
                ('categories', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['external_id'], name='media_video_externa_2ed5b6_idx')],
            },
        ),
    ]
