# Generated by Django 5.2.8 on 2026-03-03 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='media_video_slug_9d7fee_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoCategoryPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_category_links', to='media.videocategory')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_category_links', to='media.videoitem')),
            ],
        ),
        migrations.AddField(
            model_name='videoitem',
            name='categories_relation',
            field=models.ManyToManyField(related_name='videos', through='media.VideoCategoryPivot', to='media.videocategory'),
        ),
        migrations.AddIndex(
            model_name='videocategorypivot',
            index=models.Index(fields=['category', 'video'], name='media_video_categor_792a99_idx'),
        ),
        migrations.AddIndex(
            model_name='videocategorypivot',
            index=models.Index(fields=['video'], name='media_video_video_i_2f65de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videocategorypivot',
            unique_together={('video', 'category')},
        ),
    ]
