# Generated by Django 5.2.8 on 2026-03-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_videocategory_videocategorypivot_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videocategory',
            name='media_video_slug_9d7fee_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocategorypivot',
            name='media_video_video_i_2f65de_idx',
        ),
        migrations.RemoveIndex(
            model_name='videoitem',
            name='media_video_externa_2ed5b6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='videocategorypivot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='external_created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='external_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name='videocategorypivot',
            constraint=models.UniqueConstraint(fields=('video', 'category'), name='unique_video_category'),
        ),
    ]
