# Generated by Django 5.2.8 on 2026-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media', '0003_remove_videocategory_media_video_slug_9d7fee_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocategory',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
