# Generated by Django 5.2.8 on 2026-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_videocategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='link',
            field=models.TextField(max_length=300),
        ),
    ]
