# Generated by Django 5.2.8 on 2026-02-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_socialaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontent',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
