# Generated by Django 5.2.8 on 2026-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_videoitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AddIndex(
            model_name='videoitem',
            index=models.Index(fields=['link'], name='media_video_link_0fa9f6_idx'),
        ),
    ]
