# Generated by Django 5.2.8 on 2026-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_videoitem_link_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videoitem',
            index=models.Index(fields=['external_created_at'], name='media_video_externa_b72a63_idx'),
        ),
    ]
