# Generated by Django 5.2.8 on 2026-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_videoitem_media_video_externa_b72a63_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
