# Generated by Django 5.2.8 on 2026-03-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_videoitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
