# Generated by Django 5.2.8 on 2026-03-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_alter_videoitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoitem',
            name='pub_date',
        ),
    ]
