# Generated by Django 5.2.8 on 2026-03-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_remove_videoitem_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='external_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='videoitem',
            constraint=models.UniqueConstraint(fields=('external_id', 'site'), name='unique_videoitem_external_id_site'),
        ),
    ]
