# Generated by Django 5.2.8 on 2026-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_alter_videoitem_external_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='videocategorypivot',
            name='unique_video_category',
        ),
        migrations.RemoveIndex(
            model_name='videocategorypivot',
            name='media_video_categor_792a99_idx',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='categories_relation',
        ),
        migrations.AddConstraint(
            model_name='videocategorypivot',
            constraint=models.UniqueConstraint(fields=('category', 'video'), name='unique_category_video'),
        ),
    ]
