# Generated by Django 5.2.8 on 2026-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_remove_videocategorypivot_unique_video_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='slug_rewritten',
            field=models.SlugField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='title_rewritten',
            field=models.TextField(blank=True, null=True),
        ),
    ]
