# Generated by Django 5.2.8 on 2026-04-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_videoitem_slug_rewritten_videoitem_title_rewritten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='slug_rewritten',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
