# Generated by Django 5.2.8 on 2026-04-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_alter_videoitem_slug_rewritten'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('last_id', models.IntegerField()),
            ],
        ),
    ]
