# Generated by Django 5.2.8 on 2026-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_translationbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationbatch',
            name='batch_size',
            field=models.IntegerField(default=0),
        ),
    ]
