# Generated by Django 5.2.8 on 2026-04-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_translationbatch_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
