# Generated by Django 5.2.8 on 2026-04-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_videoitem_updated_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videoitem',
            index=models.Index(fields=['slug_rewritten'], name='media_video_slug_re_d6ec87_idx'),
        ),
    ]
