# Generated by Django 5.2.8 on 2026-04-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_videoitem_media_video_slug_re_d6ec87_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
