# Generated by Django 5.2.8 on 2026-04-18 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_videotranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslationBatch',
        ),
    ]
