# Generated by Django 5.2.8 on 2026-04-18 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_delete_translationbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranslation',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='videotranslation',
            name='meta_title',
        ),
    ]
