# Generated by Django 5.2.8 on 2026-05-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_remove_videotranslation_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranslation',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_relation', to='media.videoitem'),
        ),
    ]
