# Generated by Django 5.2.14 on 2026-06-08 14:41

import src.media.models.video_item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_alter_videotranslation_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='video_metadata',
            field=models.JSONField(blank=True, default=src.media.models.video_item._default_video_metadata),
        ),
    ]
