# Generated by Django 5.2.14 on 2026-06-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_videoitem_video_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videoitem',
            name='media_video_externa_b72a63_idx',
        ),
        migrations.AddIndex(
            model_name='videoitem',
            index=models.Index(fields=['categories'], name='media_video_categor_b5d063_idx'),
        ),
    ]
