# Generated by Django 5.2.14 on 2026-06-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_videoitem_video_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videoitem',
            name='media_video_externa_b72a63_idx',
        ),
    ]
