# Generated by Django 5.2.14 on 2026-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_remove_videoitem_media_video_externa_b72a63_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoitem',
            name='video_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
