# Generated by Django 5.2.14 on 2026-06-12 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0026_alter_videoitem_video_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('group', models.CharField(max_length=20)),
                ('is_in_use', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['is_in_use'], name='media_disco_is_in_u_7d2358_idx'), models.Index(fields=['group'], name='media_disco_group_258d6b_idx'), models.Index(fields=['name'], name='media_disco_name_84930a_idx'), models.Index(fields=['group', 'name'], name='media_disco_group_a8296b_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_media_discovery_tag_group_name')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph_participants', to='media.videoitem')),
                ('tags', models.ManyToManyField(blank=True, related_name='participants', to='media_discovery.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='media.videoitem')),
                ('from_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_interactions', to='media_discovery.participant')),
                ('to_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_interactions', to='media_discovery.participant')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='media_discovery.tag')),
                ('kinks', models.ManyToManyField(blank=True, related_name='kink_interactions', to='media_discovery.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['video'], name='media_disco_video_i_2052a8_idx'),
        ),
    ]
