# Generated by Django 5.2.8 on 2026-04-03 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('deleted_by_sender', models.BooleanField(default=False)),
                ('deleted_by_recipient', models.BooleanField(default=False)),
                ('read_by_sender', models.BooleanField(default=False)),
                ('read_by_recipient', models.BooleanField(default=False)),
                ('is_automated', models.BooleanField(default=True)),
                ('local_bot_id', models.CharField(max_length=20)),
                ('bot_personality', models.TextField(blank=True, null=True)),
                ('external_chat_id', models.CharField(max_length=20)),
                ('external_last_id', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboxSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auto_reply_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_ready', models.BooleanField(default=True)),
                ('file_info', models.JSONField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('llm_reply', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('sender', 'recipient'), name='conversation_unique_sender_recipient'),
        ),
    ]
