# Generated by Django 5.2.8 on 2026-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='external_last_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
