# Generated by Django 5.2.8 on 2026-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('start_id', models.BigIntegerField()),
                ('end_id', models.BigIntegerField()),
                ('url_count', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
