# Generated by Django 5.2.8 on 2026-05-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['video_id'], name='events_video_id_idx'),
        ),
    ]
