# Generated by Django 5.2.8 on 2026-04-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('message_type', models.CharField(max_length=30)),
            ],
        ),
    ]
