# Generated by Django 5.2.14 on 2026-05-14 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEmbeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raw_tag', models.CharField(max_length=255, unique=True)),
                ('canonical_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discovery.canonicaltag')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.BigIntegerField()),
                ('related_video_id', models.BigIntegerField()),
                ('similarity_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('video_id', 'related_video_id'), name='uk_video_id_related_video_id')],
            },
        ),
    ]
