# Generated by Django 5.2.14 on 2026-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagalias',
            name='rarity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tagalias',
            name='tag_group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
