# Generated by Django 5.2.14 on 2026-05-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_tagalias_rarity_score_tagalias_tag_group'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tagalias',
            index=models.Index(fields=['canonical_tag', 'tag_group'], name='canonical_tag_tag_group_idx'),
        ),
    ]
