# Generated by Django 5.2.14 on 2026-05-23 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_tagalias_canonical_tag_tag_group_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagalias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
