# Generated by Django 5.2.14 on 2026-05-23 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_tagalias_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cooccurrence_count', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tag_sources', to='discovery.canonicaltag')),
                ('target_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tag_targets', to='discovery.canonicaltag')),
            ],
            options={
                'indexes': [models.Index(fields=['source_tag', '-score'], name='related_tag_source_score_idx'), models.Index(fields=['target_tag', '-score'], name='related_tag_target_score_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_tag_id__lt', models.F('target_tag_id'))), name='related_tag_source_lt_target'), models.UniqueConstraint(fields=('source_tag', 'target_tag'), name='uk_related_tag_source_target')],
            },
        ),
    ]
