# Generated by Django 5.2.14 on 2026-05-26 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_relatedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedtag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relatedtag',
            name='cooccurrence_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
