# Generated by Django 5.2.14 on 2026-05-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_relatedtag_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relatedtag',
            name='related_tag_source_lt_target',
        ),
    ]
