# Generated by Django 5.2.14 on 2026-06-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_remove_relatedtag_related_tag_source_lt_target'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tagalias',
            name='canonical_tag_tag_group_idx',
        ),
        migrations.RemoveField(
            model_name='tagalias',
            name='tag_group',
        ),
        migrations.AddField(
            model_name='canonicaltag',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
