# Generated by Django 5.2.14 on 2026-06-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0008_remove_tagalias_canonical_tag_tag_group_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicaltag',
            name='is_gay',
            field=models.BooleanField(default=False),
        ),
    ]
