# Generated by Django 5.2.14 on 2026-06-02 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0009_canonicaltag_is_gay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canonicaltag',
            old_name='group',
            new_name='tag_group',
        ),
    ]
