# Generated by Django 5.2.14 on 2026-06-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_rename_group_canonicaltag_tag_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(unique=True)),
                ('raw_search_query', models.CharField(max_length=500)),
                ('structured_search_query', models.CharField(max_length=500)),
            ],
        ),
    ]
