# Generated by Django 5.2.14 on 2026-06-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='uuid',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
