# Generated by Django 5.2.14 on 2026-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('discovery', '0012_alter_searchquery_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagalias',
            name='occurrence_count',
            field=models.IntegerField(default=0),
        ),
    ]
