# Generated by Django 5.2.14 on 2026-06-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0013_tagalias_categories_tagalias_occurrence_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedTag',
        ),
    ]
