# Generated by Django 5.2.14 on 2026-06-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0013_tagalias_categories_tagalias_occurrence_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagalias',
            name='categories',
        ),
    ]
