# Generated by Django 5.2.14 on 2026-06-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_delete_relatedtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canonicaltag',
            name='is_gay',
        ),
    ]
