# Generated by Django 5.2.14 on 2026-06-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0015_remove_canonicaltag_is_gay'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='search_type',
            field=models.CharField(default='raw', max_length=20),
        ),
    ]
