# Generated by Django 5.2.14 on 2026-06-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0016_searchquery_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagalias',
            name='is_in_use',
            field=models.BooleanField(default=False),
        ),
    ]
