# Generated by Django 5.2.14 on 2026-06-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0017_tagalias_is_in_use'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tagalias',
            index=models.Index(fields=['is_in_use', 'raw_tag'], name='tagalias_inuse_raw_idx'),
        ),
    ]
