# Generated by Django 5.2.14 on 2026-06-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0018_tagalias_tagalias_inuse_raw_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoEmbeddings',
        ),
        migrations.DeleteModel(
            name='VideoRelationship',
        ),
    ]
